### ISSUE TITLE
Many PSMs passing the FDR filter (=0.01) have PeptideShaker scores = 0 - according to exported MzIdentML file. 

### ISSUE THREAD

**Issue by MarcIsak** [compomics/peptide-shaker-2.0-issue-tracker#48]
Hi, 

After loading a MzIdentML file (from a project that I successfully loaded into PeptideShaker 2.0.0-beta) into R, I noticed that some of the PSMs passing the FDR threshold of 0.01, had PeptideShaker scores equal to zero. I find this a little peculiar . I have attached a text file, which only contains the PSMs passing the threshold so that you can investigate this a little further.

[mzid_example.txt](https://github.com/compomics/peptide-shaker-2.0-issue-tracker/files/4040470/mzid_example.txt)
 
Harald, I shared the PeptideShaker project with you through a Dropbox link before, when you wanted to check why the saved PSDB files were corrupt. It is the same project that generated the MzIdentML I'm referring to.

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

That indeed looks strange. The PeptideShaker confidence values are all close to 100 though, so I don't think it's a problem with the data. Could you have a look at the same PSMs in the Spectrum IDs tab in PeptideShaker? You can display the scores by selecting View > Scores in the menu at the top left. This should show us if the problem is in the mzid export.

The odd part is perhaps not the zero values, but rather that all of the scores are very low. The zero values could potentially be explained by rounding?

I think I have to forward this question to my colleague @mvaudel. He's more on top of this part of the code. Hopefully it'll not become too confusing with his name being Marc as well... ;)

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, 

thanks for the quick response on this. I would just like to say that when I analyzed the same dataset in PeptideShaker v.1.16.42, the exported MzIdentML looked more reasonable. The lowest PeptideShaker score for the PSMs passing the FDR=0.01 threshold was 8.98. But for that analysis, there were no MSAmanda results but only X!Tandem and Comet. Perhaps the integration of MSAmanda into the latest SearchGUI compatible with PeptideShaker-2.0.0-beta led to some issues. 

I could also look at the scores in PeptideShaker 2.0.0-beta to see if something looks different there from the MzIdentMl.

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

> The zero values could potentially be explained by rounding?

I've looked into this, and the scores are all rounded to four decimals. Hence all scores lower than 0.00005 will end up as 0.0. I therefore assume that the scores are low in the Spectrum IDs tab as well.

The question is then why the scores are that low when the confidence is high. @mvaudel Any ideas?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

I figured out the problem. In the old version we used to transform the scores, but for some reason we do not do this anymore (at least not all the time). I will check with @mvaudel why this is the case and get back to you. In any case, if you for now focus on the confidence values and ignore the scores you should be fine.

Thanks for enabling us to locate this bug!

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Marc,

I've just updated the beta release of PeptideShaker which should take care of the issues with the zero score values: http://genesis.ugent.be/maven2/eu/isas/peptideshaker/PeptideShaker/2.0.0-beta/PeptideShaker-2.0.0-beta.zip.

It should also speed up the loading of the PSMs.

Best regards,
Harald
