### ISSUE TITLE
Large database memory usage

### ISSUE THREAD

**Issue by andrewjmc** [compomics/peptide-shaker-2.0-issue-tracker#62]
Can you relate the size of the database to the RAM consumption during loading and use? I am trying to use PeptideShaker with SearchCLI results from a modest number of spectra (few 10s of k) with a large database (target-decoy >20 Gb). I allocated 50 Gb RAM to PeptideShaker, but found it ran out of memory through ~60% of the database import process. Of note, the database is not indexed, as the indexing process on the command line also crashed.

Thanks.

**Comment by dominik-kopczynski** [comment]
Hi Andrew, sorry for the delayed answer. To create the index, you need currently main memory at least 1.5 - 2.0x as big as your fasta file additionally. We are creating the index chunk wise. However, since many intermediate steps are necessary for the index requiring auxiliary memory, this overhead will unfortunately remain.

**Comment by andrewjmc** [comment]
OK, thanks
